// <auto-generated />
using System;
using BookingApp.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200331134553_SecondCreate6")]
    partial class SecondCreate6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingApp.Models.ReservationModel", b =>
                {
                    b.Property<int>("reservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("restaurantId")
                        .HasColumnType("int");

                    b.HasKey("reservationId");

                    b.HasIndex("restaurantId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BookingApp.Models.RestaurantModel", b =>
                {
                    b.Property<int>("restaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("restaurantId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("BookingApp.Models.ReservationModel", b =>
                {
                    b.HasOne("BookingApp.Models.RestaurantModel", "restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("restaurantId");
                });
#pragma warning restore 612, 618
        }
    }
}
